import 'package:isar/isar.dart';

part 'playlist_model.g.dart';

@collection
class PlaylistModel {
  Id id = Isar.autoIncrement;
  final String playlistId;
  final String name;
  final String? description;
  final String userId;
  final List<String> songIds;
  final bool autoGenerated;
  final bool isPublic;
  final DateTime createdAt;
  final DateTime updatedAt;

  PlaylistModel({
    required this.playlistId,
    required this.name,
    this.description,
    required this.userId,
    required this.songIds,
    this.autoGenerated = false,
    this.isPublic = false,
    required this.createdAt,
    required this.updatedAt,
  });

  factory PlaylistModel.fromJson(Map<String, dynamic> json) {
    return PlaylistModel(
      playlistId: json['id'] ?? '',
      name: json['name'] ?? '',
      description: json['description'],
      userId: json['user_id'] ?? '',
      songIds:
          json['song_ids'] != null ? List<String>.from(json['song_ids']) : [],
      autoGenerated: json['auto_generated'] ?? false,
      isPublic: json['is_public'] ?? false,
      createdAt: json['created_at'] != null
          ? DateTime.parse(json['created_at'])
          : DateTime.now(),
      updatedAt: json['updated_at'] != null
          ? DateTime.parse(json['updated_at'])
          : DateTime.now(),
    );
  }

  Map<String, dynamic> toJson() {
    return {
      'id': playlistId,
      'name': name,
      'description': description,
      'userId': userId,
      'songIds': songIds,
      'autoGenerated': autoGenerated,
      'isPublic': isPublic,
      'createdAt': createdAt.toIso8601String(),
      'updatedAt': updatedAt.toIso8601String(),
    };
  }
}
