import 'package:isar/isar.dart';

part 'playlist_model.g.dart';

@collection
class PlaylistModel {
  Id id = Isar.autoIncrement;
  final String playlistId;
  final String name;
  final String userId;
  final List<String> songIds;
  final bool autoGenerated;

  PlaylistModel({
    required this.playlistId,
    required this.name,
    required this.userId,
    required this.songIds,
    this.autoGenerated = false,
  });

  factory PlaylistModel.fromJson(Map<String, dynamic> json) {
    return PlaylistModel(
      playlistId: json['id'],
      name: json['name'],
      userId: json['userId'],
      songIds: List<String>.from(json['songIds']),
      autoGenerated: json['autoGenerated'] ?? false,
    );
  }

  Map<String, dynamic> toJson() {
    return {
      'id': playlistId,
      'name': name,
      'userId': userId,
      'songIds': songIds,
      'autoGenerated': autoGenerated,
    };
  }
}