import 'package:equatable/equatable.dart';

class PlaylistEntity extends Equatable {
  final String id;
  final String name;
  final String? description;
  final String userId;
  final List<String> songIds;
  final bool autoGenerated;
  final bool isPublic;
  final String? coverUrl;
  final DateTime createdAt;
  final DateTime updatedAt;

  const PlaylistEntity({
    required this.id,
    required this.name,
    this.description,
    required this.userId,
    required this.songIds,
    this.autoGenerated = false,
    this.isPublic = false,
    this.coverUrl,
    required this.createdAt,
    required this.updatedAt,
  });

  @override
  List<Object?> get props => [
        id,
        name,
        description,
        userId,
        songIds,
        autoGenerated,
        isPublic,
        coverUrl,
        createdAt,
        updatedAt,
      ];
}
