import 'package:equatable/equatable.dart';

class PlaylistEntity extends Equatable {
  final String id;
  final String name;
  final String userId;
  final List<String> songIds;
  final bool autoGenerated;

  const PlaylistEntity({
    required this.id,
    required this.name,
    required this.userId,
    required this.songIds,
    this.autoGenerated = false,
  });

  @override
  List<Object?> get props => [id, name, userId, songIds, autoGenerated];
}