import '../../domain/entities/playlist_entity.dart';
import '../models/playlist/playlist_model.dart';

class PlaylistMapper {
  static PlaylistEntity fromModel(PlaylistModel model) {
    return PlaylistEntity(
      id: model.playlistId,
      name: model.name,
      userId: model.userId,
      songIds: model.songIds,
      autoGenerated: model.autoGenerated,
    );
  }

  static PlaylistModel toModel(PlaylistEntity entity) {
    return PlaylistModel(
      playlistId: entity.id,
      name: entity.name,
      userId: entity.userId,
      songIds: entity.songIds,
      autoGenerated: entity.autoGenerated,
    );
  }
}